import os
import sys


RLPFN_SKYLINE_POSITIVE_ENV_DEFAULTS = {
    "TICL_POLICY_CAT_FUSION": "1",
    "TICL_POLICY_SPLIT_ENCODE_FUSION": "1",
    "TICL_POLICY_FINALIZE_2D_FASTPATH": "1",
    "TICL_POLICY_STEP_PROJ_2D": "1",
    "TICL_POLICY_STEP_LAYER_2D_LOOP": "1",
    "TICL_POLICY_STEP_TOKEN_ALLOC_OPT": "1",
    "TICL_POLICY_TOKEN_LAYOUT_PREPACK": "1",
    "TICL_POLICY_TF32": "1",
    "TICL_POLICY_CACHE_CONTAINER_REUSE": "1",
    "TICL_POLICY_FUSED_TRANSITION_GENERATOR": "1",
    "TICL_POLICY_FUSED_TRANSITION_SCM_HIDDEN_FUSED": "1",
    "TICL_POLICY_TRANSITION_INNER_GROUPING": "balanced2",
    "TICL_POLICY_TRANSITION_STREAM_FUSION": "1",
    "TICL_POLICY_ROLLOUT_NOISE_STREAM": "1",
    "TICL_POLICY_ENVGEN_BMM": "1",
    "TICL_POLICY_ENVGEN_CHECKPOINT": "1",
    "TICL_POLICY_TAIL_FREEZE": "1",
    "TICL_POLICY_PREFIX_COMPACT_ON_TBPTT_DETACH": "1",
    "TICL_POLICY_FLASH_PREFIX_ASYNC": "1",
    "TICL_POLICY_FLASH_PREFIX_ZERO_FASTPATH": "1",
    "TICL_POLICY_OOM_FAIL_FAST": "1",
}


RLPFN_SKYLINE_GUARD_ENV_DEFAULTS = {
    "TICL_POLICY_PAGED_ATTN_TRAIN_MODE": "auto",
    "TICL_POLICY_PAGED_ATTN_FLASHPREFIX_DENSE_MAX_TOKENS": "64",
    "TICL_POLICY_FLASH_PREFIX_TAIL_DENSE_MAX_TOKENS": "0",
    "TICL_POLICY_FINALIZE_2D_ZERO_DROPOUT_POSTNORM_GELU_FASTPATH": "0",
    "TICL_POLICY_TRANSITION_STREAM_FUSION_MAX_GROUPS": "2",
    "TICL_POLICY_ASYNC_GROUP_COMMIT_IN_STREAM": "auto",
    "TICL_POLICY_TRANSITION_INNER_MIN_BUCKET": "0",
    "TICL_POLICY_TBPTT_STREAM_MERGE_WINDOWS": "1",
    "TICL_POLICY_TBPTT_STREAM_MERGE_AUTO": "0",
    "TICL_POLICY_ENVGEN_CHECKPOINT_REENTRANT": "0",
    "TICL_POLICY_ENVGEN_RAGGED_AFFINE": "0",
    "TICL_POLICY_INPLACE_PAGED_KV": "0",
}


def argv_targets_rlpfn(argv):
    return bool(argv) and str(argv[0]).strip().lower() == "rlpfn"


def apply_rlpfn_skyline_env_defaults(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv_targets_rlpfn(argv):
        return
    for env_map in (
        RLPFN_SKYLINE_POSITIVE_ENV_DEFAULTS,
        RLPFN_SKYLINE_GUARD_ENV_DEFAULTS,
    ):
        for key, value in env_map.items():
            os.environ.setdefault(key, value)
