#!/usr/bin/env python
"""Write the exploratory gated-wrapper contract and parity plan.

This is a planning artifact generator.  It does not sample environments, run
PPO, mutate exact-SCM defaults, or set a milestone.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from phase2_gated_reward_path_generator_wrapper import (
    RewardPathBalanceProfile,
    TopologyThresholds,
    contract_dict,
)


DEFAULT_OUTPUT_DIR = "/home/chen/RLPFN/artifacts/phase2_exploratory_gated_wrapper_contract_plan_0506"


def _json_safe(value: Any) -> Any:
    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    return value


def run(args: argparse.Namespace) -> dict[str, Any]:
    profile = RewardPathBalanceProfile.parse(args.balance_profile)
    thresholds = TopologyThresholds(
        state_gain_min=float(args.state_gain_min),
        action_gain_min=float(args.action_gain_min),
        state_to_action_ratio_max=float(args.state_to_action_ratio_max),
    )
    contract = contract_dict(profile=profile, thresholds=thresholds)
    plan = {
        "analysis_entry": "phase2_gated_wrapper_contract_plan",
        "exploratory_only": True,
        "sets_new_milestone": False,
        "contract": contract,
        "implementation_boundary": {
            "wrapper_layer": "above EnvironmentPrior._sample_batch_hypers / fixed-list generation",
            "runtime_layer": (
                "annotated h entries are interpreted only by phase2_reward_group_balance_runtime "
                "inside exploratory pack runner processes"
            ),
            "default_exact_scm_path": "unchanged",
            "default_fit_model_path": "unchanged until an explicit later migration/parity step",
            "ppo_algorithm_path": "unchanged; PPO parity is not re-proven by this wrapper plan",
        },
        "parity_plan": [
            {
                "name": "decision_table_parity",
                "scope": "environment generator wrapper only",
                "check": (
                    "For a fixed audit CSV, probe decisions must equal wrapper decisions exactly: "
                    "original_healthy_keep, width_bias_balance, reject_still_fail, and selected_balance_applied."
                ),
                "pass_condition": "zero row-level mismatches",
            },
            {
                "name": "keep_original_noop_parity",
                "scope": "environment side",
                "check": (
                    "For original_healthy_keep rows, frozen_h before/after wrapper must have no balance annotation; "
                    "a rollout through exploratory runner must match the ordinary fixed_h runner within existing "
                    "trusted pack semantics."
                ),
                "pass_condition": "same frozen_h digest and no reward-balance annotation",
            },
            {
                "name": "reward_path_only_parity",
                "scope": "environment side",
                "check": (
                    "For width_bias_balance rows, state_next and terminal/done path must match the unbalanced "
                    "transition for the same inputs/RNG; only reward path is recomputed under the annotated "
                    "state/action/noise group scales."
                ),
                "pass_condition": "state/terminal exact match; reward matches balanced runtime calculation",
            },
            {
                "name": "pack_schema_parity",
                "scope": "pack runner bridge",
                "check": (
                    "The fixed-list generated by the wrapper must be consumable by the trusted pack runner with "
                    "the same obs/reward VecNorm semantics, sidecar fields, and checkpoint-free smoke behavior."
                ),
                "pass_condition": "guard hard_pass and short smoke hard_pass under two independent seeds",
            },
            {
                "name": "fit_model_migration_parity_later",
                "scope": "future fit_model migration",
                "check": (
                    "Only after selecting this candidate, port the same wrapper contract into fit_model's "
                    "environment-batch reinitialization path while preserving fit_model vectorized family acceleration "
                    "and disabling extra objectives.  Then parity against pack runner on generated fixed lists."
                ),
                "pass_condition": "not part of current exploratory wrapper preparation",
            },
        ],
        "non_goals": [
            "No action_dim/obs_dim/state_dim sampler shrinkage.",
            "No terminal_reset_count_target change.",
            "No survival_reward change.",
            "No PPO algorithm change.",
            "No long-run generalization claim.",
        ],
        "evidence_so_far": {
            "candidate_recheck_summary": (
                "/home/chen/RLPFN/artifacts/"
                "phase2_exploratory_gated_candidate_recheck_summary_0506/"
                "gated_candidate_recheck_summary_report.json"
            ),
            "done_outlier_audit": (
                "/home/chen/RLPFN/artifacts/"
                "phase2_exploratory_gym_done_outlier_audit_0506/"
                "gym_done_outlier_audit_report.json"
            ),
        },
    }
    out_dir = Path(args.output_dir).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    report_path = out_dir / "gated_wrapper_contract_plan.json"
    report_path.write_text(json.dumps(_json_safe(plan), indent=2, sort_keys=True) + "\n", encoding="utf-8")
    md_lines = [
        "# Gated Wrapper Contract Plan",
        "",
        "Exploratory only. Does not set a new milestone.",
        "",
        "## Boundary",
        "- Wrapper sits above ordinary EnvironmentPrior sampling/fixed-list generation.",
        "- Runtime balancing is activated only by annotated frozen_h entries in exploratory runner processes.",
        "- Exact SCM defaults, terminal/survival, dimension samplers, and PPO are unchanged.",
        "",
        "## Parity Plan",
    ]
    for item in plan["parity_plan"]:
        md_lines.append(f"- {item['name']}: {item['pass_condition']}")
    md_lines.extend(
        [
            "",
            "## Non-Goals",
            *[f"- {item}" for item in plan["non_goals"]],
        ]
    )
    md_path = out_dir / "gated_wrapper_contract_plan.md"
    md_path.write_text("\n".join(md_lines) + "\n", encoding="utf-8")
    return plan


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=str, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--balance-profile", type=str, default="s3_a16_n0125:3:16:0.125")
    parser.add_argument("--state-gain-min", type=float, default=0.7)
    parser.add_argument("--action-gain-min", type=float, default=0.06)
    parser.add_argument("--state-to-action-ratio-max", type=float, default=10.0)
    args = parser.parse_args()
    report = run(args)
    print(json.dumps({"output_dir": args.output_dir, "sets_new_milestone": report["sets_new_milestone"]}, sort_keys=True))


if __name__ == "__main__":
    main()
